dnl EBVIEW_MAINTAINER_MODE ()
dnl define DISABLE_DEPRECATED
dnl
AC_DEFUN([EBVIEW_MAINTAINER_MODE],
[
	AC_REQUIRE([AM_MAINTAINER_MODE])

	if test $USE_MAINTAINER_MODE = yes; then
		DISABLE_DEPRECATED="-DG_DISABLE_DEPRECATED -DGDK_DISABLE_DEPRECATED -DGTK_DISABLE_DEPRECATED -DPANGO_DISABLE_DEPRECATED"
	else
		DISABLE_DEPRECATED=""
	fi
	AC_SUBST(DISABLE_DEPRECATED)
])
